version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
    - ./frontend:/app 
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
